import Head from 'next/head';
import Styles from '../styles/Dashboard.module.scss';

export default function Dashboard() {
  return (
    <div>
      <Head>
        <title>SisCópias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="navbar navbar-expand-lg fixed-top navbar-dark">
          <div className="container">
            <a className="navbar-brand logo-text page-scroll" href="/">
              SisCópias
            </a>
            <button
              className="navbar-toggler p-0 border-0"
              type="button"
              data-toggle="offcanvas"
            >
              <span className="navbar-toggler-icon" />
            </button>
            <div
              className="navbar-collapse offcanvas-collapse"
              id="navbarsExampleDefault"
            >
              <ul className="navbar-nav ml-auto">
                <li className="nav-item">
                  <a className="nav-link page-scroll" href="#header">
                    Home <span className="sr-only">(current)</span>
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link page-scroll" href="#features">
                    Professores
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link page-scroll" href="#details">
                    Coordenadores
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link page-scroll" href="#pricing">
                    Servidor Setor
                  </a>
                </li>
              </ul>
              <span className="nav-item">
                <div className={Styles.userBox}>
                  <img
                    className={Styles.userPhoto}
                    src="https://github.com/costapedrohenrique.png"
                    alt="perfil"
                  />
                  <span className={Styles.userName}>Pedro Henrique</span>
                </div>
              </span>
            </div>
          </div>
        </nav>
        <header className="ex-header">
          {/* <div className="container">
            <div className="row">
              <div className="col-xl-10 offset-xl-1">
                <h1 className="text-center">Login</h1>
              </div>
            </div>
          </div> */}
        </header>
      </main>
    </div>
  );
}
