import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>SisCópias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="navbar navbar-expand-lg fixed-top navbar-dark">
          <div className="container">
            <a className="navbar-brand logo-text page-scroll" href="/">
              SisCópias
            </a>
            <button
              className="navbar-toggler p-0 border-0"
              type="button"
              data-toggle="offcanvas"
            >
              <span className="navbar-toggler-icon" />
            </button>
          </div>
        </nav>

        <header className="ex-header">
          <div className="container">
            <div className="row">
              <div className="col-xl-10 offset-xl-1">
                <h1 className="text-center">Login</h1>
              </div>
            </div>
          </div>
        </header>

        <div className="ex-form-1 pt-5 pb-5">
          <div className="container">
            <div className="row">
              <div className="col-xl-6 offset-xl-3">
                <div className="text-box mt-1 mb-1">
                  <p>
                    Você não tem um cadastro?{' '}
                    <a className="blue" href="sign-up.html">
                      Solicite
                    </a>{' '}
                    agora mesmo
                  </p>

                  <form id="logInForm">
                    <div className="form-group">
                      <input
                        type="email"
                        className="form-control-input"
                        id="email"
                        required
                      />
                      {/* eslint-disable-next-line */}
                      <label className="label-control" htmlFor="email">
                        Email
                      </label>
                    </div>
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control-input"
                        id="password"
                        required
                      />
                      {/* eslint-disable-next-line */}
                      <label className="label-control" htmlFor="password">
                        Password
                      </label>
                    </div>

                    <div className="form-group">
                      <button
                        type="submit"
                        className="form-control-submit-button"
                      >
                        Login
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="footer-decoration">
          <svg
            className="footer-frame"
            data-name="Layer 1"
            xmlns="http://www.w3.org/2000/svg"
            preserveAspectRatio="none"
            viewBox="0 0 1920 115.984"
            style={{ fill: '#5f4dee' }}
          >
            <title>footer-frame</title>
            <path
              className="cls-2"
              d="M1616.28,381.705c-87.656,5.552-93.356-59.62-197.369-67.562-112.391-8.581-137.609,65.077-251.189,60.632-109.57-4.288-116.156-74.017-225.25-83.153-125.171-10.483-150,78.5-293,88.35-136.948,9.437-173.108-68.092-320.83-77.956C255.5,297.133,143,308.1,0,395.564V406.75H1920V324.537c-18-6.507-43.63-14.492-76.1-15.591C1740.655,305.452,1705.829,376.033,1616.28,381.705Z"
              transform="translate(0 -290.766)"
            />
          </svg>
        </div>

        <div className="copyright">
          <div className="container">
            <div className="row">
              <div className="col-lg-12">
                <p className="p-small">
                  Copyright ©{' '}
                  <a href="https://xvideos.com">Arthur {'<3'} Pedro</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
